/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class DOMDocument, DOMHTMLElement, NSString, UIView, WebFrameBridge;

@interface UIFieldEditor : UIView
{
    WebFrameBridge *_bridge;
    DOMDocument *_document;
    DOMHTMLElement *_textElement;
    DOMHTMLElement *_sizeElement;
    NSString *_initialText;
    NSString *_initialStyle;
    UIView *_proxiedView;
    int _selectionBehavior;
    unsigned int _changingView:1;
    unsigned int _mouseWasDragged:1;
    unsigned int _isShowingPlaceholder:1;
    unsigned int _shouldMaintainFirstResponderWhenEndEditing:1;
    unsigned int _isResigningFirstResponder:1;
    unsigned int _delegateRespondsToFieldEditorDidChange:1;
    unsigned int _delegateRespondsToShouldInsertText:1;
    unsigned int _delegateRespondsToShouldReplaceWithText:1;
    unsigned int _fieldEditorReentrancyGuard:1;
    unsigned int _reserved:23;
}

+ (id)activeFieldEditor;	// IMP=0x323fd250
+ (void)releaseSharedInstance;	// IMP=0x323fd2f8
+ (id)sharedFieldEditor;	// IMP=0x323fd260
- (id)_proxyPlaceholderStyle;	// IMP=0x323fdae8
- (id)_proxyPlaceholderText;	// IMP=0x323fdac4
- (BOOL)_proxySupportsPlaceholderText;	// IMP=0x323fda94
- (id)_responderForBecomeFirstResponder;	// IMP=0x323fd8d0
- (void)_setTextElementString:(id)fp8;	// IMP=0x323fe08c
- (void)_setTextElementStyle:(id)fp8;	// IMP=0x323fde2c
- (BOOL)_setupPlaceholderText;	// IMP=0x323fdb3c
- (void)autoscrollTimerFired:(id)fp8;	// IMP=0x323ff050
- (void)becomeFieldEditorForView:(id)fp8 inRect:(struct CGRect)fp12;	// IMP=0x323ff7b4
- (unsigned int)becomeFirstResponder;	// IMP=0x323fd680
- (BOOL)canResignFirstResponder;	// IMP=0x323fd628
- (unsigned int)characterOffsetAtPoint:(struct CGPoint)fp8;	// IMP=0x323fda2c
- (void)clearPlaceholder;	// IMP=0x323ff5b8
- (struct CGSize)contentSize;	// IMP=0x323fe734
- (void)dealloc;	// IMP=0x323fd53c
- (BOOL)hasMarkedText;	// IMP=0x323fec9c
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x323fd394
- (BOOL)isProxyFor:(id)fp8;	// IMP=0x323ff03c
- (BOOL)isShowingPlaceholder;	// IMP=0x323fdfc8
- (id)keyboardInputOverlayContainer:(id)fp8;	// IMP=0x323fdd4c
- (void)maintainFieldEditorWhenEndEditingForView:(id)fp8;	// IMP=0x323fddd0
- (void)mouseDown:(struct __GSEvent *)fp8;	// IMP=0x323fee7c
- (void)mouseDragged:(struct __GSEvent *)fp8;	// IMP=0x323feefc
- (void)mouseUp:(struct __GSEvent *)fp8;	// IMP=0x323fef7c
- (id)proxiedView;	// IMP=0x323fecd4
- (BOOL)resignFirstResponder;	// IMP=0x323fd754
- (void)resumeWithNotification:(id)fp8;	// IMP=0x323ff220
- (void)scrollToMakeCaretVisible:(BOOL)fp8;	// IMP=0x323fe7c8
- (int)scrollXOffset;	// IMP=0x323fe490
- (int)scrollYOffset;	// IMP=0x323fe4c4
- (void)selectAll;	// IMP=0x323fd5dc
- (int)selectionBehavior;	// IMP=0x323fda24
- (struct _NSRange)selectionRange;	// IMP=0x323fd8ec
- (void)setCaretColor:(struct CGColor *)fp8;	// IMP=0x323fe43c
- (void)setFrame:(struct CGRect)fp8;	// IMP=0x323fecdc
- (void)setScrollXOffset:(int)fp8 scrollYOffset:(int)fp12;	// IMP=0x323fe4f8
- (void)setScrollXOffset:(int)fp8 scrollYOffset:(int)fp12 adjustForPurpleCaret:(BOOL)fp16;	// IMP=0x323fe524
- (void)setSelection:(struct _NSRange)fp8;	// IMP=0x323fd934
- (void)setSelectionBehavior:(int)fp8;	// IMP=0x323fd9f8
- (void)setStyle:(id)fp8;	// IMP=0x323fdeb8
- (void)setText:(id)fp8;	// IMP=0x323fe168
- (void)setupPlaceholderTextIfNeeded;	// IMP=0x323fec50
- (BOOL)shouldChangeSelectionForEvent:(struct __GSEvent *)fp8;	// IMP=0x323fd8d8
- (id)style;	// IMP=0x323fdfd8
- (id)text;	// IMP=0x323fe268
- (struct CGColor *)textColorForCaretSelection;	// IMP=0x323fe038
- (id)textTraits;	// IMP=0x323fdcac
- (void)webView:(id)fp8 didFinishLoadForFrame:(id)fp12;	// IMP=0x323fe590
- (BOOL)webView:(id)fp8 shouldChangeSelectedDOMRange:(id)fp12 toDOMRange:(id)fp16 affinity:(int)fp20 stillSelecting:(BOOL)fp24;	// IMP=0x323ff650
- (BOOL)webView:(id)fp8 shouldDeleteDOMRange:(id)fp12;	// IMP=0x323fead8
- (BOOL)webView:(id)fp8 shouldInsertText:(id)fp12 replacingDOMRange:(id)fp16 givenAction:(int)fp20;	// IMP=0x323ff290
- (void)webViewDidBeginEditing:(id)fp8;	// IMP=0x323fea40
- (void)webViewDidChange:(id)fp8;	// IMP=0x323fe9a8
- (void)webViewDidChangeSelection:(id)fp8;	// IMP=0x323fe9f4
- (void)webViewDidEndEditing:(id)fp8;	// IMP=0x323fea8c

@end

