/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface UIGradient : NSObject
{
    CDAnonymousStruct3 *_values;
    float _height;
    struct CGShading *_shader;
}

- (void)dealloc;	// IMP=0x323f00cc
- (void)fillRect:(struct CGRect)fp8;	// IMP=0x323f0070
- (void)fillRect:(struct CGRect)fp8 inContext:(struct CGContext *)fp24;	// IMP=0x323f0234
- (id)initVerticalWithValues:(CDAnonymousStruct3 *)fp8;	// IMP=0x323eff70

@end

