/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSString, UIView;

@interface UIViewController : NSObject
{
    UIView *_view;
    NSString *_navigationTitle;
    id _parentController;
    unsigned int _observeApplicationSuspendResume:1;
    unsigned int _reserved:31;
}

+ (struct CGRect)defaultViewFrame;
- (id)init;
- (id)initWithView:(id)fp8 navigationTitle:(id)fp12;
- (void)dealloc;
- (struct CGRect)defaultViewFrame;
- (struct CGRect)_childViewFrame;
- (id)view;
- (void)addViewToSuperview:(id)fp8;
- (void)removeViewFromSuperview;
- (void)_setParentController:(id)fp8;
- (id)_parentController;
- (id)navigationController;
- (id)buttonBarController;
- (BOOL)isSnapBackForIdentifier:(id)fp8 userInfo:(id)fp12;
- (void)viewWillDisplayWithAnimation:(BOOL)fp8;
- (void)viewWasAddedToSuperview;
- (void)viewDidDisplayWithAnimation:(BOOL)fp8;
- (void)viewWillHideWithAnimation:(BOOL)fp8;
- (void)viewDidHideWithAnimation:(BOOL)fp8;
- (void)tearDownUIForReason:(int)fp8;
- (void)_setObserveApplicationSuspendResume:(BOOL)fp8;
- (void)applicationWillSuspend;
- (void)_applicationDidSuspend;
- (void)_applicationDidSuspendEventsOnly;
- (void)applicationDidResume;
- (void)_applicationDidResumeEventsOnly;
- (void)didReceiveMemoryWarning;
- (BOOL)_recursivelyPresentOverlay:(id)fp8 andHideViewController:(id)fp12 animate:(BOOL)fp16 transition:(int)fp20;
- (BOOL)_recursivelyDismissOverlay:(id)fp8 andRedisplayViewController:(id)fp12 animate:(BOOL)fp16 transition:(int)fp20;
- (void)_setNavigationTitle:(id)fp8;

@end

